app = "iys-sgd-api"
primary_region = "bom"

[build]
  dockerfile = "Dockerfile"

[deploy]
release_command = "python manage.py migrate --noinput"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_080
min_machines_running = 0

[[vm]]
cpus = 1
memory = "512mb"
